

CREATE TABLE OARUSER(
EMAIL VARCHAR2(50) CONSTRAINT OARUSER_PK PRIMARY KEY,
PASSWORD VARCHAR2(50) CONSTRAINT PASS_WORD_NN NOT NULL,
ROLE VARCHAR2(10)
);

INSERT INTO OARUSER(EMAIL,PASSWORD,ROLE) VALUES('roy@admin.com','1234','admin');

INSERT INTO OARUSER(EMAIL,PASSWORD,ROLE) VALUES('bhavani@admin.com','1234','admin');

INSERT INTO OARUSER(EMAIL,PASSWORD,ROLE) VALUES('pramila@admin.com','1234','admin');

INSERT INTO OARUSER(EMAIL,PASSWORD,ROLE) VALUES('test1@test.com','1234','traveller');

INSERT INTO OARUSER(EMAIL,PASSWORD,ROLE) VALUES('test2@test.com','1234','traveller');

INSERT INTO OARUSER(EMAIL,PASSWORD,ROLE) VALUES('test3@test.com','1234','traveller');




CREATE TABLE OARUSERDETAILS(
REGISTRATIONID VARCHAR2(50) CONSTRAINT REGISTRATIONID_PK PRIMARY KEY,
EMAIL VARCHAR2(50) NOT NULL,
CONSTRAINT OARUSERDETAILS_FK FOREIGN KEY (EMAIL) REFERENCES OARUSER(EMAIL),
FIRSTNAME VARCHAR(30) CONSTRAINT FIRST_NAME_NN NOT NULL,
LASTNAME VARCHAR(10),
DOB VARCHAR(10) NOT NULL,
PANNO VARCHAR2(10) CONSTRAINT USERPAN NOT NULL,
GENDER CHAR(2) CONSTRAINT USERDOBCK CHECK(GENDER IN('F','f','M','m')),
ACCOUNTNUMBER VARCHAR2(50) CONSTRAINT USERACC NOT NULL,
BANKNAME VARCHAR2(20) CONSTRAINT USERBNAME NOT NULL,
BRANCHNAME VARCHAR2(20) CONSTRAINT USERBRNAME NOT NULL,
CONTACTONE VARCHAR2(20) NOT NULL,
CONTACTTWO VARCHAR2(20),
ADDRESS VARCHAR2(70) CONSTRAINT USERADDRESS NOT NULL,
CUST_CERTIFICATE_NUMBER VARCHAR2(15) CONSTRAINT USERCCNUN UNIQUE,
STATUS_APPROVAL CHAR DEFAULT 'N'
);

INSERT INTO OARUSERDETAILS VALUES('123456','test1@test.com','test1','','22-MAR-1993','chpf1234','M','4591919919191919','sbi','abids',0000000000,0000,'test address',12345678,'N');

INSERT INTO OARUSERDETAILS VALUES('123457','test2@test.com','test2','','20-JUL-1993','chpf1235','F','4594519919191919','sbi','abids',0000000000,0000,'test address',12345428,'N');

update oaruserdetails set status_approval='Y' where email='test1@test.com';


CREATE TABLE OARFLIGHTS(
FLIGHTID VARCHAR2(10) CONSTRAINT OARFLIGHTS_PK PRIMARY KEY,
FLIGHTNAME VARCHAR2(20) CONSTRAINT OARFLIGHTS_NN NOT NULL,
FLIGHTTYPE VARCHAR2(20) CONSTRAINT OARFLIGHT_TYPE_NN NOT NULL,
ARRIVAL_TIME VARCHAR2(20),
DEPARTURE_TIME VARCHAR2(20),
SOURCE VARCHAR2(15) CONSTRAINT FLIGHTS_SRC NOT NULL,
DESTINATION VARCHAR2(15) CONSTRAINT FLIGHTS_DEST NOT NULL,
CAPACITY NUMBER(4) DEFAULT 100,
FARE NUMBER(9) DEFAULT 3000
);

insert into oarflights(flightid,flightname,flighttype,arrival_time,departure_time,source,destination,capacity,fare) 
values('KB123','KINGHB','KING BIRD','11:00','9:00','hyd','ban','1000','4343');

insert into oarflights(flightid,flightname,flighttype,arrival_time,departure_time,source,destination,capacity,fare) 
values('KB124','KINGDB','KING BIRD','12:00','10:00','del','ban','1000','8743');

insert into oarflights(flightid,flightname,flighttype,arrival_time,departure_time,source,destination,capacity,fare) 
values('KB125','KINGHC','KING BIRD','15:00','14:00','hyd','chen','1000','8756');

insert into oarflights(flightid,flightname,flighttype,arrival_time,departure_time,source,destination,capacity,fare) 
values('QB135','QUEENBHC','QUEEN BIRD','16:00','12:00','hyd','chen','700','9056');

insert into oarflights(flightid,flightname,flighttype,arrival_time,departure_time,source,destination,capacity,fare) 
values('QB165','QUEENBCD','QUEEN BIRD','17:00','16:05','chen','del','700','5046');

insert into oarflights(flightid,flightname,flighttype,arrival_time,departure_time,source,destination,capacity,fare) 
values('QB185','QUEENBDB','QUEEN BIRD','17:45','16:30','del','ban','700','2356');

insert into oarflights(flightid,flightname,flighttype,arrival_time,departure_time,source,destination,capacity,fare) 
values('PB223','PRINCEBBC','PRINCE BIRD','11:00','10:00','ban','chen','500','5789');

insert into oarflights(flightid,flightname,flighttype,arrival_time,departure_time,source,destination,capacity,fare) 
values('PB224','PRINCEBCD','PRINCE BIRD','7:00','6:05','chen','del','500','9846');

insert into oarflights(flightid,flightname,flighttype,arrival_time,departure_time,source,destination,capacity,fare) 
values('PB225','PRINCEBDC','PRINCE BIRD','8:45','7:30','del','ban','500','3466');


CREATE TABLE TRNX(
TRANX VARCHAR2(50) CONSTRAINT OARTRNX_PK PRIMARY KEY,
USEREMAIL VARCHAR2(50) NOT NULL,
CONSTRAINT OARTRANX_USER_FK FOREIGN KEY (USEREMAIL) REFERENCES OARUSER(EMAIL),
FLIGHTID VARCHAR2(10) NOT NULL,
CONSTRAINT OARTRANX_FLIGHT_FK FOREIGN KEY (FLIGHTID) REFERENCES OARFLIGHTS(FLIGHTID),
BOOKINGDATE VARCHAR2(20),
JOURNEYDATE VARCHAR2(20) CONSTRAINT JD_NN NOT NULL,
FARE NUMBER(15) DEFAULT '0',
STATUS_APPROVAL VARCHAR2(4) DEFAULT 'N'
);

INSERT INTO TRNX(TRANX,USEREMAIL,FLIGHTID,BOOKINGDATE,JOURNEYDATE,FARE,STATUS_APPROVAL) VALUES('1111','test2@test.com','KB123',SYSDATE,'12-JUN-2015',1,'6000','N');
INSERT INTO TRNX(TRANX,USEREMAIL,FLIGHTID,BOOKINGDATE,JOURNEYDATE,NUMBEROFTICKETS,FARE,STATUS_APPROVAL) VALUES('ABC124XYZ','test2@test.com','KB123',SYSDATE,'12-JUN-2015',1,'6000','N');



-------------------------------------------------------------------------------------
CREATE TABLE OARBOOKINGDETAILS(
TID VARCHAR2(50) NOT NULL,
CONSTRAINT OARBOOKINGDETAILS_FK FOREIGN KEY (TID) REFERENCES TRNX(TRANX),
FLIGHTID VARCHAR2(10) NOT NULL,
CONSTRAINT BOOKINGDETAILS_FLIGHT_FK FOREIGN KEY (FLIGHTID) REFERENCES OARFLIGHTS(FLIGHTID),
SEATNUMBER NUMBER(3) NOT NULL,
CONSTRAINT BOOKINGDETAILS_PK PRIMARY KEY (FLIGHTID, SEATNUMBER),
PASSENGERNAME VARCHAR(50) NOT NULL,
AGE NUMBER(2),
STATUS CHAR
);























